version: '2'

services:

  angular: 
    build:
      context: .
      dockerfile: ./src.dockerfile
    ports:
      - "4200:4200"
  express:
    build: 
      context: .
      dockerfile: ./server.dockerfile
    ports:
      - "3000:3000"
    links: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
